### PR TITLE
made it good

### PR DESCRIPTION
**Pull request by Yeetface513**
;)

### CODE REVIEW

**Comment by AverageComet250** [comment]
I have an issue with this. Your graph code is shit. Make it better first.

**Comment by Yeetface513** [comment]
My graph code is fine

**Comment by Yeetface513** [comment]
pls

**Comment by AverageComet250** [comment]
Please do not double post. Because of your indecency to respect basic internet etiquette I am closing this pull request. 

Thanks.

**Comment by Yeetface513** [comment]
noooo pls

**Comment by Yeetface513** [comment]
why you bully me

**Comment by Yeetface513** [comment]
what did I do wrong

**Comment by Yeetface513** [comment]
I fixed it pls

**Comment by Yeetface513** [comment]
bro accept it pls :) @AverageComet250 @AverageComet250 @AverageComet250

**Comment by AverageComet250** [comment]
Will now merge. Thanks for changes.

**Pull request merged**
